import type { Metadata } from 'next';
import { Poppins } from '@next/font/google';
import './globals.css';
import Navbar from '@/components/layout/navbar/page';
import Footer from '@/components/layout/footer/footer';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '700'], // specify the weights you want
});

export const metadata: Metadata = {
  title: 'Nyami Nyami',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Poppins.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
      <Footer />
    </html>
  );
}
